CREATE TABLE students_writing (
   num INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   topik VARCHAR(20) not NULL,
   title VARCHAR(100) NOT NULL,
   img VARCHAR(255),
   CONTENT VARCHAR(1000) NOT NULL,
   writer VARCHAR(50) NOT NULL,
   userimg VARCHAR(255),
   date DATE DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE shop_writing (
   num INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   pay VARCHAR(20) NOT NULL,
   title VARCHAR(100) NOT NULL,
   img VARCHAR(255),
   content VARCHAR(1000) NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   upload_date DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE free_writing (
   num INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   topik VARCHAR(20) not NULL,
   title VARCHAR(100) NOT NULL,
   img VARCHAR(255),
   CONTENT VARCHAR(1000) NOT NULL,
   NAME VARCHAR(50) NOT NULL,
   userimg VARCHAR(255) NOT null
   date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE admin_writing (
    num INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(20) not NULL,
   title VARCHAR(100) NOT NULL,
   img VARCHAR(255),
   CONTENT VARCHAR(1000) NOT NULL,
   date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE admin (
   num INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   pass VARCHAR(10) NOT NULL
);

CREATE TABLE comments (
  comment_id INT(100) PRIMARY KEY AUTO_INCREMENT,
  post_id INT(100) NOT NULL,
  content VARCHAR(1000) NOT NULL,
  writer VARCHAR(50) NOT NULL,
  userimg VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE note (
   num INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(50) NOT NULL,
   CONTENT VARCHAR(500) NOT NULL,
   toname VARCHAR(50) NOT NULL,
   DATE VARCHAR(50)
);

CREATE TABLE students (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  studentNumber VARCHAR(20) NOT NULL,
  password VARCHAR(20) NOT NULL,
  email VARCHAR(200) NOT NULL,
  grade VARCHAR(20) NOT NULL,
  position VARCHAR(20) NOT NULL,
  approval_status VARCHAR(10) DEFAULT '미승인',
  img VARCHAR(255) DEFAULT 'images/profile.png'
);